# frozen_string_literal: true

source 'https://rubygems.org'

gem 'moneykit', '~> 0.1.0'

gem 'puma', '~> 6.4'
gem 'sinatra', '~> 4.2'

gem 'rubocop', '~> 1.50', group: :development

gem 'debug', '~> 1.7', group: :development

gem 'dotenv', '~> 2.8'

gem "sinatra-cors", "~> 1.2"

gem "activesupport", "~> 7.1"

gem "jwt", "~> 2.7"
