# frozen_string_literal: true

source 'https://rubygems.org'

gem 'moneykit', '~> 0.1.0'

gem 'puma', '~> 6.3'
gem 'sinatra', '~> 3.0'

gem 'rubocop', '~> 1.50', group: :development

gem 'debug', '~> 1.7', group: :development

gem 'dotenv', '~> 2.8'

gem "sinatra-cors", "~> 1.2"
