services:
  python:
    build:
      context: python
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - "./python:/app/"

  ruby:
    build:
      context: ruby
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - "./ruby:/app/"
