"""Initial models

Revision ID: 8eb30795d8fd
Revises:
Create Date: 2023-04-25 13:23:20.986008

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8eb30795d8fd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("moneykit_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "user_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("institution_id", sa.String(), nullable=False),
        sa.Column("institution_name", sa.String(), nullable=False),
        sa.Column("transaction_sync_cursor", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_links_user_id"), "user_links", ["user_id"], unique=False)
    op.create_table(
        "financial_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_link_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("moneykit_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("account_number_masked", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_link_id"],
            ["user_links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("moneykit_id"),
    )
    op.create_index(op.f("ix_financial_accounts_user_link_id"), "financial_accounts", ["user_link_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("financial_account_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("moneykit_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("timestamp", sa.Date(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["financial_account_id"],
            ["financial_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("moneykit_id"),
    )
    op.create_index(
        op.f("ix_transactions_financial_account_id"), "transactions", ["financial_account_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_financial_account_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_financial_accounts_user_link_id"), table_name="financial_accounts")
    op.drop_table("financial_accounts")
    op.drop_index(op.f("ix_user_links_user_id"), table_name="user_links")
    op.drop_table("user_links")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
