# frozen_string_literal: true

source 'https://rubygems.org'

gem 'moneykit', '~> 0.2.2'

gem 'rubocop', '~> 1.50', group: :development

gem 'debug', '~> 1.7', group: :development

gem 'dotenv', '~> 2.8'

gem "sinatra-cors", "~> 1.2"

gem "dry-cli", "~> 1.0"

gem "awesome_print", "~> 1.9"
