version: "3"

services:
  backend-python:
    build:
      context: backend_python
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      BASE_URL: http://localhost:8000
      DATABASE_ECHO_SQL: "false"
      DATABASE_URL: postgresql://postgres:password@db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - "./backend_python/budgeting_app:/app/budgeting_app"
      - "./backend_python/migrations:/app/migrations"

  db:
    image: postgres:13.4
    volumes:
      - db-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  db-data:
