services:
  backend_python:
    build:
      context: backend/python
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      FRONTEND_OAUTH_REDIRECT_URI: http://localhost:3000
    networks:
      - create_link
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - "./backend/python/app:/app/app"

  backend_python_without_sdk:
    build:
      context: backend/python_without_sdk
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      FRONTEND_OAUTH_REDIRECT_URI: http://localhost:3000
    networks:
      - create_link
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - "./backend/python_without_sdk/app:/app/app"

  backend_ruby:
    build:
      context: backend/ruby
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      FRONTEND_OAUTH_REDIRECT_URI: http://localhost:3000
    networks:
      - create_link
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - "./backend/ruby:/app/"

  frontend_web:
    build:
      context: frontend/web
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - create_link
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

networks:
  create_link:
    name: create_link
