version: "3"

services:
  backend-python:
    build:
      context: backend_python
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      BASE_URL: http://localhost:8000
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - "./backend_python/app:/app/app"
