services:
  python:
    build:
      context: python
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - "./python:/app/"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      HOST_IP: host.docker.internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
