[tool.poetry]
name = "fetch_products"
version = "0.1.0"
description = ""
authors = ["MoneyKit"]
readme = "README.md"

[tool.poetry.scripts]
mk = 'cli:run'

[tool.poetry.dependencies]
python = "^3.11"
moneykit = { version = "^0.1.0a1", allow-prereleases = true }
typer = "^0.9.0"
rich = "^13.7.0"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
